services:
  template:
    hostname: template
    container_name: template
    restart: always
    image: temp/late:latest
    ports:
      - "80:80"
    environment:
      TEST: "testvar"
    volumes:
      - ./local/path:/container/path
    networks:
      - testnet
    labels:
      test.label: "testvar"

networks:
  testnet:
    external: true