services:
  tsdproxy:
    container_name: "proxy"
    hostname: "proxy"
    image: almeidapaulopt/tsdproxy:2
    restart: unless-stopped
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config

networks:
  proxy:
    external: true

volumes:
  datadir: