services:
  homepage:
    hostname: homepage
    container_name: homepage
    restart: always
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - pinet
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "homepage"

networks:
  pinet:
    external: true