title: Hercules

background:
  image: https://images.unsplash.com/photo-1723810307048-249a74afb2db?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  opacity: 65
  blur: sm

theme: dark

color: slate

useEqualHeights: true

headerStyle: boxed

statusStyle: "dot"