- resources:
    cpu: true
    cputemp: true
    uptime: true
    units: metric
    network: eth0
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    locale: de
    format:
      hourCycle: h23
      dateStyle: short
      timeStyle: short

- logo:
    icon: sh-raspberry-pi