services:
  romm:
    image: rommapp/romm:3.7.2
    container_name: romm
    restart: ${RP_ROMM}
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm-user
      - DB_PASSWD=${DB_PASSWD}
      - ROMM_AUTH_SECRET_KEY=${AUTH_KEY}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
      - MOBYGAMES_API_KEY=${MOBYGAMES_API_KEY}
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY}
      - TZ=${TZ}
      - OIDC_ENABLED=${OIDC_ENABLED}
      - OIDC_PROVIDER=${OIDC_PROVIDER}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_REDIRECT_URI=${OIDC_REDIRECT_URI}
      - OIDC_SERVER_APPLICATION_URL=${OIDC_SERVER_APPLICATION_URL}
      - DISABLE_USERPASS_LOGIN=${DISABLE_USERPASS_LOGIN}
    volumes:
      - romm_resources:/romm/resources
      - romm_redis_data:/redis-data
      - ${LIBRARY}:/romm/library
      - ${ASSETS}:/romm/assets
      - ${CONFIG}:/romm/config
    ports:
      - ${HOST_PORT}:8080
    networks:
      - usenet
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: ${RP_DB}
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=${DB_PASSWD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - usenet
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

networks:
  usenet:
    name: ${NET_NAME}
    external: ${EXT_NET}