name: gitea
services:
  gitea:
    image: docker.gitea.com/gitea:latest
    ports:
      - "222:22"
      - "3003:3000"
    restart: unless-stopped
    container_name: gitea
    hostname: gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "gitea"
      tsdproxy.autodetect: "false"
      tsdproxy.port: "3002"
      tsdproxy.dash.icon: "sh/gitea"
      glance.name: Gitea
      glance.icon: sh:gitea
      glance.url: https://gitea.ojos-sole.ts.net
      glance.description: gitea
      glance.id: gitea
    networks:
      - proxy

networks:
  proxy:
    external: true