# This is a basic workflow to help you get started with Actions

name: PushCompose

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy Docker Compose projects to raspi4b
      - name: Deploy Docker Compose projects to raspi4b
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Loop through all subdirectories containing docker-compose.yml
          for dir in $(find . -type f -name 'docker-compose.yml' -exec dirname {} \;); do
            echo "Processing directory: $dir"

            # Copy the directory to the remote host
            scp -r "$dir" avii@raspi4b:/home/avii/

            # SSH into the remote host and deploy the Docker Compose project
            ssh avii@raspi4b << EOF
              cd /home/avii/$(basename "$dir")
              docker compose down
              docker compose pull
              docker compose up -d
          EOF
          done