name: Deploy to Raspberry Pi

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
        - name: Checkout repository
            uses: actions/checkout@v3

        - name: Set up SSH
            uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Deploy all Docker Compose projects to Raspberry Pi
            run: |
                for dir in $(find . -type d -name '*'); do
                    if [ -f "$dir/docker-compose.yml" ]; then
                        scp -r "$dir" avii@raspi4b:/home/avii/
                        ssh avii@raspi4b << 'EOF'
                        cd /home/avii/$(basename "$dir")
                        docker-compose down
                        docker-compose pull
                        docker-compose up -d
                        EOF
                    fi
                done